// sidebars.js
module.exports = {
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Version 1.0 - Core Backend',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'modules', // This points to docs/modules
        },
      ],
    },
    {
      type: 'category',
      label: 'System Logs (Answers)',
      collapsed: true, // Keep it collapsed by default so it doesn't clutter the UI
      items: [
        {
          type: 'autogenerated',
          dirName: 'answers', // This points to docs/answers
        },
      ],
    },
  ],
};